apiVersion: v1
kind: Service
metadata:
  labels:
    name: kafka-topic-webhook
  name: kafka-topic-webhook
  namespace: myproject
spec:
  ports:
    - name: https
      port: 443
      targetPort: 8443
  selector:
    name: kafka-topic-webhook
  type: ClusterIP
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-topic-webhook
  labels:
    name: kafka-topic-webhook
  namespace: myproject
spec:
  replicas: 1
  template:
    metadata:
      name: kafka-topic-webhook
      labels:
        name: kafka-topic-webhook
    spec:
      containers:
        - image: scholzj/kafka-topic-webhook:latest
          name: kafka-topic-webhook
          env:
            - name: ZOOKEEPER_URL
              value: kafka-zookeeper:2181
          ports:
            - containerPort: 8443
              name: https
---

apiVersion: admissionregistration.k8s.io/v1alpha1
kind: ExternalAdmissionHookConfiguration
metadata:
  name: kafka-topic-webhook
externalAdmissionHooks:
- name: topic-webhook.kafka.scholz.cz
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  failurePolicy: Fail
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURPakNDQWlLZ0F3SUJBZ0lVVjAxM3JNYW5XMDUvb01iMi96OCtmdEdnTU1nd0RRWUpLb1pJaHZjTkFRRUwKQlFBd05URUxNQWtHQTFVRUJoTUNRMW94RHpBTkJnTlZCQWNUQmxCeVlXZDFaVEVWTUJNR0ExVUVDaE1NU21GcgpkV0lnVTJOb2IyeDZNQjRYRFRFM01USXpNVEl4TkRBd01Gb1hEVEl5TVRJek1ESXhOREF3TUZvd05URUxNQWtHCkExVUVCaE1DUTFveER6QU5CZ05WQkFjVEJsQnlZV2QxWlRFVk1CTUdBMVVFQ2hNTVNtRnJkV0lnVTJOb2IyeDYKTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFwWi9GMHdNdmhrNXlkcU44K3lqZApDNW9wTDNVYnZkQ1kzTHlUN3VvWmpudzNJQXB0cnUyekZhQzRIVFBzUHRydDExNGZLTkpQYy9WWXZEdk1zWVBKClBjK0tTNlo2dy9pbklacDltOXdKaE9YTTRWTnpaN2JVSGhPM01hbmR5cVpwQWNQU21YZjRSMkFYRlRBMGNNNk4Kd280QnNWMkVYT0lRNlJ3bC80Q2dmR2U2ZUJodGJ0ZkVINTdWMTRpNWNYdW9Kd1lXRzA4aXVzNW9QaVU1OEM1OAovUHE5Rlg2czEwUmthUlZWUmNFaEp3cjNEOHVDeEo1ZTJYNXJhTHY4c2ZrOFZhZUlhZVQxKzhIMXpLZDdFMEZFClBRdlU2MldxVklkRGlaL1pqTnpuWlJ6RVVDVXBFZjZ3WXlRL29RdHR0SlpjMnpIaHFZUnhHSGRqR2pxZzJJSDUKN1FJREFRQUJvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBUVl3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVgpIUTRFRmdRVTd3dCtHb0dPcmNQV0EzWDNGY3RVc1BKQnVYY3dEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQzVuCk43aFpGS0pnOVJmUzRHUUdFU1krU0UyRnhnNjZSM2JiTGkzdU9ORzZ5ZzFTQ2JvTFlmRVFWOVNpSnJJOGhoSG0KOXRoT3JwbnJNdUE2Z25WVlpleWlFNDA4Q0FBTFZIYWRobXdIc0xmNWdmQ1J0MWNyL0QxclppTnYrVkdaclZFbgpnZ3QvV1MzaVZZSkpIRi91aWVsRXpVVHJjdWNoYkNtRFV1MnJtM1ZZd0FaV3RUOGJ5US93UHkxdk5DNFR2M2ZxCjEyaWlNWXZIV0thMXNnZVBmZElqMHd1cHRGQlVLbElaQkRRWjE3Tk9kU1N0NkdRZklaUTNiTXV2K1YwM3pxdGEKaGRCb2ZBZjJrRXNkeEhoMnVCcVBHUFgvUUwzRHRMNDRiaVlYL2tMVDBRVE5uVVJ2eEFBZ3dHcWpvV2dxSm5McwpFNWJPZDVNZ2dLUEFscllIaE5rPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: kafka-topic-webhook
      namespace: myproject
