apiVersion: v1
kind: Service
metadata:
  labels:
    name: kafka-topic-initializer
  name: kafka-topic-initializer
  namespace: myproject
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    name: kafka-topic-initializer
  type: ClusterIP
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-topic-initializer
  labels:
    name: kafka-topic-initializer
  namespace: myproject
spec:
  replicas: 1
  template:
    metadata:
      name: kafka-topic-initializer
      labels:
        name: kafka-topic-initializer
    spec:
      containers:
        - image: scholzj/kafka-topic-initializer:latest
          name: kafka-topic-initializer
          env:
            - name: ZOOKEEPER_URL
              value: zookeeper:2181
          ports:
            - containerPort: 8080
              name: http
---

apiVersion: admissionregistration.k8s.io/v1alpha1
kind: ExternalAdmissionHookConfiguration
metadata:
  name: kafka-topic-initializer
externalAdmissionHooks:
- name: topic-initializer.kafka.scholz.cz
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  failurePolicy: Fail
  clientConfig:
    service:
      name: kafka-topic-initializer
      namespace: myproject