apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-consumer
spec:
  replicas: 1
  template:
    metadata:
      labels:
      annotations:
        topic-webhook.kafka.scholz.cz/topics: "[ {\"name\": \"topicX\", \"create\": true, \"assert\": false, \"partitions\": 3, \"replicas\": 3, \"config\": { \"cleanup.policy\": \"compact\" } } ]"
    spec:
      containers:
      - name: kafka-consumer
        image: scholzj/kafka-consumer:latest
        env:
          - name: BOOTSTRAP_SERVERS
            value: kafka:9092
          - name: TOPIC
            value: topicX
          - name: GROUP_ID
            value: my-kafka-consumer