apiVersion: v1
kind: Service
metadata:
  labels:
    name: kafka-topic-webhook
  name: kafka-topic-webhook
  namespace: default
spec:
  ports:
    - name: https
      port: 443
      targetPort: 8443
  selector:
    name: kafka-topic-webhook
  type: ClusterIP
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-topic-webhook
  labels:
    name: kafka-topic-webhook
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      name: kafka-topic-webhook
      labels:
        name: kafka-topic-webhook
    spec:
      containers:
        - image: scholzj/kafka-topic-webhook:latest
          name: kafka-topic-webhook
          env:
            - name: ZOOKEEPER_URL
              value: kafka-zookeeper:2181
          ports:
            - containerPort: 8443
              name: https
---

apiVersion: admissionregistration.k8s.io/v1alpha1
kind: ExternalAdmissionHookConfiguration
metadata:
  name: kafka-topic-webhook
externalAdmissionHooks:
- name: topic-webhook.kafka.scholz.cz
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  failurePolicy: Ignore
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURPakNDQWlLZ0F3SUJBZ0lVYUpFbFBhdFgxcDIxY0pMZVNvWkJ3N0d3MElNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd05URUxNQWtHQTFVRUJoTUNRMW94RHpBTkJnTlZCQWNUQmxCeVlXZDFaVEVWTUJNR0ExVUVDaE1NU21GcgpkV0lnVTJOb2IyeDZNQjRYRFRFM01USXpNVEl5TURrd01Gb1hEVEl5TVRJek1ESXlNRGt3TUZvd05URUxNQWtHCkExVUVCaE1DUTFveER6QU5CZ05WQkFjVEJsQnlZV2QxWlRFVk1CTUdBMVVFQ2hNTVNtRnJkV0lnVTJOb2IyeDYKTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF3cnIzVDZod1lRYm5ZY2g2aTc2SAoxbTdTOHZVQ0JDWDVyVmc3UDBPM2dCSmVSKzROYnB2eUlxTWdIL0w4TE1iOXNQZXZGdy9laUNxWFVxS0ZuMnZHCmxSdnBGZW9tRFp3TVFZQkpSUGxOdm0wYWxaT2NtdjVHRFpNc285OGpsbVBadndaMFVDRm5MaWxnRFUwc1dwTzAKNEtlRlhwTlBJTE51dGwyRUtkSVpWdUVSSUtMZ2lzSGl2NUxjRDlRK2hnUlAvQlVsS1p2K1RvajdCRDZzcHI3VwpKRTFTQWtrbjNsODBYN0R4UjlWSVBuekxGbXJ1WU1qTjQ1SEtrNHllR254Unc5WkRtTmpkazV0VzVaSE5qV2M0CjZQcURyN09LY0lISlJvTy9SeG5CcFQzV3NBRnIzRFd0SlpOdE1mVEhWc29uSmpTQ242NzNoZzRpNDhDUWpVWUwKQ3dJREFRQUJvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBUVl3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVgpIUTRFRmdRVU8ydGIrN1NFY0twZkNYY2N0Q01lVHdzVzU0QXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSzgwCnZZQTBkR3hTa29IQ1d5S2pqeGVsYlkyblp0TzZEZEhGbUl1UU5KVHRmeEhBMk0xTUtsd0grMXR3bXNDck1GWEsKUXpNWklyN3cveEpYOVUvN0F1R2p4enVYa0NtY0VaZk1qQ0FqY2VCR1VsVE9qckRSNU4rdFBVcjhldm10b0tXRgpQMkF4YWxtVzhZOFlISmlpMWRKdzVucitBZTFuSURaa2hNVlN2TXBydTlxQzRLamV3ZE9HajRoMnlKYXdUYStzCnRueHJTOHc4Nmw3YWc4dXdyTEY1eFFEbHFod1VFR1g5MVBOcVJLV0tVU1IzOTBnU1JIalNmK2tZZUdTdyt5LysKT3AzOXpsS3BOSUlnRDV3aHMvZ1pMWFZxemZ3Vk0xL1ZpNFdpOTdueEhVZkxQSEpMck9WaUFxbTFoMktsZmJMeQphYkNFcGJJeWpWb1BpM2didjRNPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: kafka-topic-webhook
      namespace: default
